export const SET_ALL_INGREDIENTS = "SET_ALL_INGREDIENTS";
export const FILTER_INGREDIENTS = "FILTER_INGREDIENTS";
export const ADD_INGREDIENTS = "ADD_INGREDIENTS";
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENTS";
